### ISSUE TITLE
Feature request: An 'allow navigation' type option?

### ISSUE THREAD

**Issue by ddamico-cbc** [Allov/rc.component.dialoger#1]
I've recently been asked to alter WAM behaviour so that clicking on an element in our main navigation (which is left exposed while dialogs are showing) would perform that navigation, rather than closing the dialog and cancelling the navigation, which is the current behaviour of Dialoger. Could we perhaps make this something configurable on init? Something like this would serve...

```
Dialoger.prototype.init = function(config) {
    var self = this;

    self.$dialogElement = getDialogElement();
    self.config = config || {};

    router.navigating.subscribe(this.canNavigate, this);
};

Dialoger.prototype.canNavigate = function() {
    // We assume that no links are possible in a dialog and the only navigation possible
    // would be by the back button.
    // So, in that case, we cancel navigation and simply close the dialog.
    var self = this;
    var currentDialog = this.currentDialog();

    if (currentDialog) {
        currentDialog.settings.close(null);
        if (self.config.allowNavigation) {
            return true;
        } else {
            return false;
        }
    }

    return true;
};
```

...but as always, I am very open to alternative suggestions that would get us to a solution. Or, in this case, alternative takes on what the problem actually is. Maybe I am trying to solve the wrong thing?

**Comment by RCMax** [comment]
Yes. 

Can you make the modification? 

To prevent from creating a breaking change, I think we should put a default value of false to this configuration.

**Comment by ddamico-cbc** [comment]
Thanks Max, I just pushed 0.3.1.
